version: "3.7"
services:
  interface:
    build:
      context: ./
      dockerfile: docker/interface.dockerfile
    env_file:
      - .env
    container_name: ${APP_CONTAINER_NAME}-${APP_ENV}
    hostname: ${APP_CONTAINER_NAME}-${APP_ENV}
    ports:
      - "${APP_PORT}:5000"
    volumes:
      - ./app:/app/
      - ${CHFAKT2_PATH}:/chfakt2/
    command: ["flask", "run"]
    restart: unless-stopped